# Generated by Django 4.1.3 on 2023-01-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
